INPUT OLD_DATA
LOAD OLD_DATA
L1:N2: DIV DOIS
L1:N2: COPY DOIS,TMP_DATA
STORE  NEW_DATA
N1:
aDD doiS ;Depois testar com N2:aDD doiS
MULT DOIS
STORE TMP_DATA
LOAD OLD_DATA
SUB TMP_DATA
             
STORE TMP_DATA
OUTPUT TMP_DATA
COPY NEW_DATA, OLD_DATA
LOAD OLD_DATA
JMPP L1
STOP
DOIS: CONST 2
OLD_DATA: SPACE
NEW_DATA: SPACE
TMP_DATA: SPACE